name: Flutter Build DEBUG APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'
          channel: 'stable'

      # --- FULLY CORRECTED STEPS ---

      - name: Install Firebase CLI
        # This step is required for the flutterfire command to authenticate
        run: npm install -g firebase-tools

      - name: Decode google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > ${{ github.workspace }}/android/app/google-services.json

      - name: Create .env file
        run: echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env

      - name: Activate FlutterFire CLI
        run: dart pub global activate flutterfire_cli

      - name: Generate Firebase Options
        # We must provide the FIREBASE_TOKEN for this command to log in
        run: flutterfire configure --project=${{ secrets.FIREBASE_PROJECT_ID }} --yes --platforms=android
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # --- END OF CORRECTED STEPS ---

      - name: Get dependencies
        run: flutter pub get

      - name: Build DEBUG APK
        # The command is correct: 'build apk' with no --release flag
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
