name: Flutter Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'
          channel: 'stable'

      # --- NEW AND CORRECTED STEPS START HERE ---

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Decode google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > ${{ github.workspace }}/android/app/google-services.json
      
      # NEW: Create the .env file from our GitHub secret
      - name: Create .env file
        run: echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env

      - name: Activate FlutterFire CLI
        run: dart pub global activate flutterfire_cli

      - name: Generate Firebase Options
        run: flutterfire configure --project=${{ secrets.FIREBASE_PROJECT_ID }} --yes --platforms=android
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # --- NEW AND CORRECTED STEPS END HERE ---

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
